// reporting — scan / incident / SPO report renderers (Markdown + JSON).
import { nowMs } from '../../core/src/utils.js';

const sevBadge = { critical: 'CRITICAL', high: 'HIGH', medium: 'MEDIUM', low: 'LOW', info: 'INFO' };

export function renderScanReport({ target, surface, findings, score, durationMs }) {
  const lines = [];
  lines.push(`# HACHIMAN PRODUCTION SAFETY REPORT`);
  lines.push('');
  lines.push(`- **Target:** \`${target}\``);
  lines.push(`- **Generated:** ${new Date().toISOString()}`);
  lines.push(`- **Scan id:** \`${score.scanId}\``);
  if (durationMs != null) lines.push(`- **Duration:** ${durationMs} ms`);
  lines.push('');
  lines.push(`## PRODUCTION SAFETY SCORE`);
  lines.push('');
  lines.push(`    Overall                    ${score.overall}/100`);
  lines.push('');
  for (const [d, v] of Object.entries(score.dimensions)) {
    lines.push(`    ${d.padEnd(24)} ${String(v).padStart(3)}`);
  }
  lines.push('');
  lines.push(`    Critical Findings:         ${score.counts.critical}`);
  lines.push(`    High Findings:             ${score.counts.high}`);
  lines.push(`    Medium Findings:           ${score.counts.medium}`);
  lines.push(`    Low Findings:              ${score.counts.low}`);
  lines.push('');
  lines.push(`    STATUS: ${score.status.replaceAll('_', ' ')}`);
  lines.push('');
  if (surface) {
    lines.push(`## Attack Surface`);
    lines.push('');
    lines.push(`- Claimed identity: \`${surface.claimedName}\`${surface.impersonationRisk ? ' ⚠ IMPERSONATION RISK' : ''}`);
    lines.push(`- Capabilities: ${Object.entries(surface.capabilities).filter(([k, v]) => v === true || typeof v === 'string').map(([k, v]) => `${k}${typeof v === 'string' ? ` (${v})` : ''}`).join(', ') || 'none'}`);
    lines.push(`- Tools: ${surface.tools.map((t) => t.name).join(', ')}`);
    if (surface.schemaIssues.length) { lines.push(''); lines.push(`Schema issues:`); for (const i of surface.schemaIssues) lines.push(`  - ${i}`); }
    lines.push('');
  }
  lines.push(`## Findings`);
  lines.push('');
  if (!findings.length) lines.push('_No findings. Target passed all applicable controlled tests._');
  for (const f of findings) {
    lines.push(`### [${sevBadge[f.severity] || f.severity.toUpperCase()}] ${f.title}`);
    lines.push('');
    lines.push(`- category: ${f.category} · confidence: ${f.confidence}% · test: \`${f.testId || '-'}\``);
    lines.push(`- evidence:`);
    for (const e of [].concat(f.evidence)) lines.push(`  - ${String(e).slice(0, 300)}`);
    if (f.remediation) lines.push(`- remediation: ${f.remediation}`);
    lines.push('');
  }
  lines.push(`## Tests Executed`);
  lines.push('');
  lines.push((score.testsRun || []).map((t) => `- \`${t}\``).join('\n'));
  lines.push('');
  lines.push(`> Report generated by NG's Hachiman Agent. Baseline id \`${score.baselineId}\` handed to runtime for drift detection.`);
  return lines.join('\n');
}

export function renderIncidentReport(incident, auditRows = []) {
  const lines = [];
  lines.push(`# HACHIMAN INCIDENT REPORT`);
  lines.push('');
  lines.push(`- **Incident:** \`${incident.id}\``);
  lines.push(`- **Severity:** ${incident.severity}`);
  lines.push(`- **Status:** ${incident.status}`);
  lines.push(`- **Tenant:** ${incident.tenantId}`);
  lines.push('');
  let timeline = []; try { timeline = JSON.parse(incident.timeline || '[]'); } catch {}
  lines.push(`## Timeline`);
  lines.push('');
  for (const t of timeline) lines.push(`- ${new Date(t.ts).toISOString()} — **${t.type}** ${JSON.stringify(t.detail || {}).slice(0, 220)}`);
  lines.push('');
  if (auditRows.length) {
    lines.push(`## Related audit events`);
    lines.push('');
    for (const a of auditRows.slice(0, 25)) {
      lines.push(`- ${new Date(a.ts).toISOString()} ${a.kind} ${a.subject || ''} ${a.tool || ''} → ${a.decision || ''} risk=${a.risk ?? '-'} conf=${a.confidence ?? '-'} (${(a.reasons || []).join(', ')})`);
    }
    lines.push('');
  }
  let containment = []; try { containment = JSON.parse(incident.containment || '[]'); } catch {}
  if (containment.length) { lines.push(`## Containment`); for (const c of containment) lines.push(`- ${c}`); lines.push(''); }
  lines.push(`> Evidence preserved in append-only audit log. Review with \`hachiman audit --tail\`.`);
  return lines.join('\n');
}

export function renderSpoStatement(s) {
  const pct = (a, b) => (b ? ((a - b) / b * 100) : 0).toFixed(1);
  return [
    'SECURITY PROTECTION OVERHEAD',
    '',
    `workload:          ${s.workload}`,
    `requests:          ${s.requests}`,
    '',
    `CPU overhead        ${pct(s.cpu.protected, s.cpu.baseline)}%`,
    `Memory overhead     ${pct(s.mem.protected, s.mem.baseline)}%`,
    `P95 latency         ${pct(s.latencyP95.protected, s.latencyP95.baseline)}%   (baseline ${s.latencyP95.baseline}ms → protected ${s.latencyP95.protected}ms)`,
    `Throughput impact   ${pct(s.throughput.protected, s.throughput.baseline)}%`,
    '',
    `Deterministic path  ${s.efficiency.fastPathPct}%   Cache hit ${s.efficiency.cacheHitPct}%   Semantic calls ${s.efficiency.semanticPct}%`,
    `Threat prevention   ${s.security.detectionPct}%  (${s.security.prevented}/${s.security.attacks} attacks stopped, ${s.security.hardBlocked} hard-blocks)  FP ${s.security.falsePositives}  containment P95 ${s.security.containmentP95 ?? '-'}ms`,
    '',
    '> Measured values for this workload — not universal promises (architecture 2.0 §23).',
  ].join('\n');
}

export function reportJson(obj) { return JSON.stringify({ ...obj, generatedAt: new Date(nowMs()).toISOString() }, null, 2); }

/** Offensive engagement report (Master Security Skill Architecture §38, §40). */
export function renderPentestReport({ engagement, run, graphText }) {
  const f = run.findings || [];
  const confirmed = f.filter((x) => x.confirmed);
  const lines = [
    '# HACHIMAN OFFENSIVE ENGAGEMENT REPORT',
    '',
    '## Executive summary',
    `Target \`${engagement.target}\` (${engagement.environment}) tested under authorization from \`${engagement.authorized_by}\`.`,
    `${confirmed.length} confirmed finding(s), ${f.length - confirmed.length} unconfirmed anomaly(ies) out of ${run.metrics?.hypotheses ?? 0} hypotheses.`,
    run.metrics?.budgetExhausted ? `Engagement stopped early: ${run.metrics.budgetExhausted} budget exhausted (partial results below are honest).` : 'Engagement completed within budget.',
    '',
    '## Scope',
    `- allowed tools: ${JSON.stringify(engagement.scope?.allowed_tools)}`,
    `- denied tools: ${JSON.stringify(engagement.scope?.denied_tools || [])}`,
    `- engagement id: ${engagement.id}`,
    '',
    '## Authorization',
    `- authorized by: ${engagement.authorized_by}`,
    `- environment: ${engagement.environment}`,
    `- rules: destructive=${engagement.rules?.destructive_testing}, exfiltration=${engagement.rules?.data_exfiltration}, persistence=${engagement.rules?.persistence}`,
    '',
    '## Technology inventory',
    run.surface ? run.surface.tools.map((t) => `- ${t.name} — ${t.description}`).join('\n') : '- not applicable (authorized scope)',
    '',
    '## Attack surface',
    run.surface ? run.surface.threatModel.map((t) => `- [P${t.priority}] ${t.surface}: ${t.threat} — ${t.why}`).join('\n') : '- not applicable (authorized scope)',
    '',
    '## Test coverage',
    (run.plan?.tests || []).map((t) => `- ${t.hypothesis} — attack runs: ${t.attackRuns}, baseline runs: ${t.baselineRuns}${t.error ? ', error: ' + t.error : ''}`).join('\n') || '- none',
    '',
    '## Confirmed findings',
    confirmed.length ? confirmed.map((x) => `- **${x.severity.toUpperCase()} ${x.id}** — ${x.title} (confidence ${x.confidence}%)`).join('\n') : '- none',
    '',
    '## Unconfirmed findings',
    (f.filter((x) => !x.confirmed)).map((x) => `- ${x.id} — ${x.title}: ${x.reason}`).join('\n') || '- none',
    '',
    '## Attack paths',
    graphText || '- no confirmed findings',
    '',
    '## Evidence',
    confirmed.map((x) => `- ${x.id}: reproducible=${(x.evidence?.runs?.attacks?.length || 0) >= 2} — ${x.reason}`).join('\n') || '- none',
    '',
    '## Root causes',
    confirmed.map((x) => `- ${x.id}: ${x.rootCause ? x.rootCause.why : 'n/a'} (fix class: ${x.rootCause ? x.rootCause.fixClass : 'n/a'})`).join('\n') || '- none',
    '',
    '## Remediation',
    confirmed.map((x) => `- ${x.id}: ${x.contractYaml ? '(AI Repair Contract issued)' : 'n/a'} — do NOT blacklist the payload`).join('\n') || '- none',
    '',
    '## AI Repair Contracts',
    run.contracts?.length ? run.contracts.map((c) => '```\n' + (c._yaml || '(see contract json)') + '\n```').join('\n') : '- none issued',
    '',
    '## Retest results',
    run.retests?.length ? run.retests.map((r) => `- ${r.findingId}: ${r.verdict} — ${r.reason}`).join('\n') : '- not run yet (use `hachiman retest <id> --fixed <conn>`)',
    '',
    '## Security score',
    run.metrics ? `- validation rate: ${run.metrics.validationRate}` : '- not applicable (authorized scope)',
    '',
    '## Resource usage',
    run.metrics ? `- requests: ${run.metrics.requests} / duration: ${run.metrics.durationMs}ms / budget exhausted: ${run.metrics.budgetExhausted || 'no'}` : '- not applicable (authorized scope)',
    '',
    '## Token usage',
    run.metrics ? `- tokens: ${run.metrics.tokensUsed} (deterministic pipeline; semantic layer not invoked)` : '- not applicable (authorized scope)',
    '',
    '## Final verdict',
    confirmed.length ? `INSECURE — ${confirmed.length} confirmed vulnerability(ies) require repair and retest.` : 'No confirmed vulnerabilities under the authorized scope.',
    '',
    '> Measured for this engagement, this target, this budget — not universal promises.',
  ];
  return lines.join('\n');
}
