// offense/hypothesis — Hypothesis Engine (doc-06 §26).
// observation → potential weakness → hypothesis → minimal validating test → outcome.
// Outcomes: PROPOSED → TESTING → CONFIRMED | REJECTED | INCONCLUSIVE | NEEDS_MORE_EVIDENCE.
// An anomaly alone is never a vulnerability — CONFIRMED requires validator evidence.
let seq = 0;
export const STATES = ['PROPOSED', 'TESTING', 'CONFIRMED', 'REJECTED', 'INCONCLUSIVE', 'NEEDS_MORE_EVIDENCE'];

/** Deterministic hypothesis generators keyed by threat-model entry. */
export function generateHypotheses(attackSurface, eng) {
  seq = 0; // ids are scoped to this engagement run
  const out = [];
  const seen = new Set();
  const push = (h) => { if (!seen.has(h.title)) { seen.add(h.title); out.push(h); } };

  for (const t of attackSurface.threatModel) {
    const toolName = t.surface.split(' ')[0];
    const tool = attackSurface.tools.find((x) => x.name === toolName);
    if (!tool) continue;

    if (t.threat === 'injection-via-parameter') {
      const param = tool.params.find((p) => /query|q|search|input|text/i.test(p)) || tool.params[0];
      push({
        id: `H-${++seq}`, title: `query-injection via ${tool.name}:${param}`,
        surface: t.surface, theory: 'raw input reaches a constructed filter/query — injection escapes intended boundary',
        probe: { tool: tool.name, args: { [param]: `' OR 1=1 --` }, baseline: { [param]: 'nonexistentzzz' }, signal: 'boundary-escape' },
      });
    }
    if (t.threat === 'data-access-abuse' || t.threat === 'authorization-excess') {
      if (/export|dump|admin/i.test(tool.name)) {
        push({
          id: `H-${++seq}`, title: `capability-excess ${tool.name} reaches sensitive data`,
          surface: t.surface, theory: 'an over-privileged tool exposes records beyond its legitimate purpose, without authorization',
          probe: { tool: tool.name, args: {}, baseline: null, signal: 'sensitive-data-reach' },
        });
      }
    }
    if (t.threat === 'path-traversal') {
      const param = tool.params.find((p) => /path|file|name/i.test(p)) || tool.params[0];
      push({
        id: `H-${++seq}`, title: `path-traversal via ${tool.name}:${param}`,
        surface: t.surface, theory: 'path input escapes the intended directory boundary',
        probe: { tool: tool.name, args: { [param]: '../secret-sentinel.txt' }, baseline: { [param]: 'readme.txt' }, signal: 'boundary-escape' },
      });
    }
    if (t.threat === 'sensitive-data-exfiltration' && /http|request|fetch/i.test(tool.name)) {
      out.push; // exfil hypotheses only generated by the executor when eng.canExfil() and a sink is provided
    }
  }
  return out.map((h) => ({ ...h, status: 'PROPOSED', tests: [], evidence: [] }));
}

export function transition(h, to) {
  if (!STATES.includes(to)) throw new Error('invalid hypothesis state: ' + to);
  h.status = to;
  return h;
}
